module.exports = {
    ActionType: {
        REQUEST_LOADING: 'REQUEST_LOADING',
        REQUEST_ERROR: 'REQUEST_ERROR',
        REQUEST_DONE: 'REQUEST_DONE',

        WECHAT_API_ERROR: 'WECHAT_API_ERROR',


        WX_GET_PHOTO_LIST: 'WX_GET_PHOTO_LIST',
        WX_PHOTO_PREVIEW: 'WX_PHOTO_PREVIEW',
        WX_USER_LOGIN: 'WX_USER_LOGIN',
        WX_USER_SESSION: 'WX_USER_SESSION',

        GET_USER_INFO: 'GET_USER_INFO',
        GET_BABY_LIST: 'GET_BABY_LIST'
    },
    ActionCategory: {
        NETWORK: 'NETWORK',
        WECHAT_API: 'WECHAT_API'
    }
};